#!/bin/bash
#SBATCH --time=0-00:30:00    # 0 hours 30 minutes
#SBATCH --mem-per-cpu=500    # 500MB of memory

MECHAFM=$WRKDIR/MechAFM/bin/mechafm-omp
MAKEBINARY=$WRKDIR/varmad1/MechAFM/myCode/toyDB/twoAtoms/makeBinaryHDF5.py
OUTPUTAFM=$WRKDIR/varmad1/MechAFM/myCode/toyDB/twoAtoms/output/

cd $OUTPUTAFM

for i in *; do
    cd $i
    $MECHAFM *.scan ./
    python $MAKEBINARY -i *.scan -o ./
    rm scan*
    cd ..
done
