#!/bin/bash
#SBATCH --time=0-04:00:00    # 4 hours 00 minutes
#SBATCH --mem-per-cpu=2000    # 2000MB of memory

MECHAFM=$WRKDIR/MechAFM/bin/mechafm-omp
MAKEBINARY=$WRKDIR/varmad1/MechAFM/myCode/toyDB/twoDiffAtomsFC/makeBinaryHDF5.py
OUTPUTAFM=$WRKDIR/varmad1/MechAFM/myCode/toyDB/twoDiffAtomsFC/output/

cd $OUTPUTAFM

for i in *; do
    cd $i
    $MECHAFM *.scan ./
    python $MAKEBINARY -i *.scan -o ./
    rm scan*
    cd ..
done
