import struct
import glob
import argparse
import h5py

parser = argparse.ArgumentParser(description="Take a folder with the .AFM files generated by makeBinary.py and compile all the files into one .AFMDATA file")
parser.add_argument("-i", "--input_folder", default="input.scan", help="the path to the input .SCAN file (default: %(default)s)")
args = parser.parse_args()


if not args.input_folder.endswith('/'):
    inFolder = args.input_folder+'/'
else:
    inFolder = args.input_folder

moleculename = inFolder[:-1].split("/")[-1]

f = h5py.File(moleculename + '.hdf5', "a")                                              # Name of compiled binary file

f.create_group('molecule' + moleculename[-6:])

for i in range(100):
    g = h5py.File(inFolder + "out%d.hdf5"%(i), "r")                                     # Iterates through all HDF5 files and reads all the data into the main binary file
    #f.create_group('molecule' + moleculename[-6:])
    orientationstring = 'molecule' + moleculename[-6:] + "/orientation%d"%(i)           # Assumption that the molecules are named 'dsgdb9nsd_000001' Last 6 characters are selected
    fzarray = g[orientationstring + '/fzvals']
    atomPosition = g[orientationstring + '/atomPosition']

    atomNameString = g[orientationstring].attrs["atomNameString"]
    widthxyz = g[orientationstring].attrs["widthxyz"]
    dxyz = g[orientationstring].attrs["dxyz"]
    divxyz = g[orientationstring].attrs["divxyz"]
    zLowzHigh = g[orientationstring].attrs["zLowzHigh"]
    

    dsetfz = f.create_dataset(orientationstring+'/fzvals', fzarray.shape)
    dsetfz[...] = fzarray
    #dsetsol = f.create_dataset(orientationstring+'/solution', solutionarray.shape)
    #dsetsol[...] = solutionarray
    dsetpos = f.create_dataset(orientationstring+'/atomPosition', atomPosition.shape)
    dsetpos[...] = atomPosition

    f[orientationstring].attrs['atomNameString'] = atomNameString # This might be redundant, but it is saved along with the atom positi
    f[orientationstring].attrs['widthxyz'] = widthxyz
    f[orientationstring].attrs['dxyz'] = dxyz
    f[orientationstring].attrs['divxyz'] = divxyz
    f[orientationstring].attrs['zLowzHigh'] = zLowzHigh
