#!/bin/bash
#SBATCH --time=0-02:00:00    # 2 hours 00 minutes
#SBATCH --mem-per-cpu=1000    # 1000MB of memory

MECHAFM=$WRKDIR/MechAFM/bin/mechafm-omp
MAKEBINARY=$WRKDIR/varmad1/MechAFM/myCode/toyDB/makeBinaryHDF5.py
OUTPUTAFM=$WRKDIR/varmad1/MechAFM/myCode/toyDB/output/

cd $OUTPUTAFM

for i in *; do
    cd $i
    $MECHAFM *.scan ./
    python $MAKEBINARY -i *.scan -o ./
    rm scan*
    cd ..
done
